# 1. База даних
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "django_user"
        - name: POSTGRES_PASSWORD
          value: "mypassword123" # Встанови будь-який пароль тут
---
# 2. Сервіс бази (без змін)
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
---
# 3. Твій додаток
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twiiter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twiiter
  template:
    metadata:
      labels:
        app: twiiter
    spec:
      containers:
      - name: twiiter-container
        image: twiiterclone:local
        imagePullPolicy: Never
        env:
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "django_user"
        - name: DB_PASS
          value: "mypassword123" # МАЄ БУТИ ТАКИМ ЖЕ, ЯК ВИЩЕ
        - name: DB_HOST
          value: "db"
        ports:
        - containerPort: 8000
